### ISSUE TITLE
TAG Review planning

### ISSUE THREAD

**Issue by majido** [WICG/scroll-boundary-behavior#13]
Blink API owner have asked for a TAG review of this feature before its launch. I am planning to submit the following review request to TAG. Please take a look and suggest any modification before I send the request.

-----------------------------------------------

Hello TAG!

I'm requesting a TAG review of:

  - Name: scroll-boundary-behavior
  - Specification URL: https://wicg.github.io/scroll-boundary-behavior/
  - Explainer, Requirements Doc, or Example code: https://github.com/WICG/scroll-boundary-behavior
  - Tests: not available but we have [plans](https://bugs.chromium.org/p/chromium/issues/detail?id=762054) to upstream existing tests.
  - Primary contacts: @bgirard, @majido

Further details (optional):

  - Relevant time constraints or deadlines: We like to ship this feature in Chrome M63 (feature freeze in 24 days)
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/majido/scroll-boundary-behavior/blob/security-considerations/security-privacy-questionnaire.md).
  - [ ] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

The current design is the result of discussion with various CSSWG and WICG members. 
You can see relevant discussion on this CSSWG [github issue](https://github.com/w3c/csswg-drafts/issues/769) and WICG [discourse thread](https://discourse.wicg.io/t/generic-scroll-chaining-prevention-mechanism-or-expand-standardize-ms-scroll-chaining/1811).

We have a working prototype implemented in [Chromium](https://groups.google.com/a/chromium.org/d/msg/blink-dev/OqBNF2efmFA/3ByBUKyaCgAJ) behind web platform experimental features flags. The API has received positive feedback from [Edge](https://github.com/w3c/csswg-drafts/issues/769#issuecomment-270228948)  and [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=951793#c11) and addresses a real need from web developers [here](https://github.com/w3c/csswg-drafts/issues/769#issuecomment-279832555) and [here](https://github.com/w3c/csswg-drafts/issues/769#issuecomment-288878908). 

We'd prefer the TAG provide feedback as (please select one):

  - [] open issues in our Github repo for each point of feedback
  - [] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting_

For background, some decent explainers:

  https://github.com/w3c/ServiceWorker/blob/master/explainer.md
  https://github.com/zkoch/paymentrequest/blob/gh-pages/docs/explainer.md
  https://github.com/WICG/IntersectionObserver/blob/gh-pages/explainer.md (although this one includes IDL, which an explainer should not)

**Comment by majido** [comment]
@bgirard  PTAL and let me know if you want me to change anything before submission. I like to submit this to TAG as soon as possible (perhaps in 24 hours) to give them enough time for review. In fact we should have probably requested a TAG review sooner but given that this is a small feature I am hopeful that it won't take much time to review. :)

**Comment by bgirard** [comment]
That's an excellent summary. I'm not familiar with the TAG process so I'll follow along :).
