### ISSUE TITLE
Shorthand syntax when -x and -y values are distinct

### ISSUE THREAD

**Issue by ewilligers** [WICG/scroll-boundary-behavior#18]
The syntax for scroll-boundary-behavior does not support distinct
values for scroll-boundary-behavior-x and scroll-boundary-behavior-y.

An author might set scroll-boundary-behavior-x and scroll-boundary-behavior-y
to distinct values, and then read the computed style's scroll-boundary-behavior.

Chrome (with experimental features enabled)
supports distinct values for parsing but not for output.
https://jsfiddle.net/ericwilligers/0c94qyo4/

**Comment by majido** [comment]
Thanks for catching this issue! To be fair, when designing `scroll-boundary-behavior` we were looking at 
`overflow` which does not support distinct values for its longhands. But it seems that `overflow` behavior is just legacy. So I think we should just support the propper model of doing longhands.
