### ISSUE TITLE
What should the spec say about programmatic scrolling?

### ISSUE THREAD

**Issue by bgirard** [WICG/scroll-boundary-behavior#6]
I don't think I've seen any browser trigger any scroll boundary default actions such as scroll chaining, over scroll affordances or navigation action as a result of programatic scrolling.

Options that I'm considering
1) Leave it unspecified or not mention programmatic at all. Thus it would imply option 2) since user/programmatic is never disambiguated.
2) Require both user and programatic scroll to have MUST level requirement.
3) Require MUST for user, should for programmatic
4) Require MUST for user, does not apply for programmatic

I think given that programatic scrolling doesn't trigger anything that this property covers 1) may actually be the best option. This way if programatic scrolling ever does trigger this action then we can decide that's the best behavior for it then.

**Comment by majido** [comment]
AFAIK all programmatic scrolling methods (e.g., those `Window` and `Element`) clamped the passed in scroll offsets to the actual scrollable amount (See for [example](https://drafts.csswg.org/cssom-view/#scroll-an-element)). So there is never any scroll amount left that causes chaining which means the specified boundary behavior is never exercised.

Given this I am in favor of (1) perhaps with a note mentioning the above.

**Comment by bgirard** [comment]
https://github.com/WICG/scroll-boundary-behavior/commit/69a2f65da3c01ed8071ffefaf3fa42a21ae32ecc

I've added the following sentence:
Note: Programmatic scrolling is clamped and can not trigger any <a>boundary default actions</a>.

I've avoided talking about scrollable amount because scrolling might not be pixel based and could be momentum based. I think keeping that abstract is more flexible. Please re-open if you'd like the wording to be changed.
