### ISSUE TITLE
Be more explicit about page-navigation gestures

### ISSUE THREAD

**Issue by staktrace** [WICG/scroll-boundary-behavior#7]
Just a minor nit. In the definition of `Boundary default action` you explicitly mention `performing a navigation action` as a possible boundary default action. Therefore I think it would be good also explicitly mention that in the `none` behavior alongside overscroll affordances.

**Comment by bgirard** [comment]
I was on the fence about this and ultimately left it out for no good reason. Since you pointed it out I'll add it.

**Comment by bgirard** [comment]
Please re-open if you think the wording should be changed.
