### ISSUE TITLE
Preventing navigation should happen with "contain"

### ISSUE THREAD

**Issue by majido** [WICG/scroll-boundary-behavior#8]
With the current wording preventing navigation on top level viewport requires using `none` but IMHO it should not. I suggest moving that to `contain` instead and making the difference between `contain` and `none` to only be the disabling of overscroll affordance.

I think we should encourage developers to keep the overscroll affordance (it is better UX) except when they actually want to disable it. So preventing navigation should not automatically result in disabling overscroll affordance. 

I wonder if the right way to think about this is to not consider "overscroll affordance" as a "Boundary default action". Or perhaps there are two classes of boundary default actions (local, non-local). In which case:

- `auto`: up to browser
- `contain`: prevents (non-local) boundary default action (i.e., chaining and navigations) but allows overscroll affordance.
- `none`: same as contain by also prevents overscroll affordance (local boundary default action).

**Comment by bgirard** [comment]
Thank you for pointing that out. I agree and I'll try to clarify it.

**Comment by bgirard** [comment]
I prefer the local, non-local refinement since it's a perfect partition and works well with `contain` containing the event and preventing non-local default action. I imagine it will also naturally apply to any type of boundary default actions that may be introduced in the future.

**Comment by bgirard** [comment]
I've added a definition for non-local boundary default action and amended the value definitions. Let me know if you think there needs to be more edits.
